### ISSUE TITLE
Missing dist-folder in npm

### ISSUE THREAD

**Issue by TrygveUrdahl** [appzic/esbuild-plugin-styled-components#11]
It looks like the recently published version 3.0.0 is missing the `dist` folder in npm, causing the package not to work. 

See here: https://www.npmjs.com/package/esbuild-plugin-styled-components/v/3.0.0?activeTab=code

**Comment by y-developer** [comment]
Thanks for pointing out the issue with version 3.0.0. I've addressed it by adding the prepublishOnly script to ensure the build step is not forgotten.  The npm package has been updated to **v3.0.1**. Your feedback is incredibly helpful!
